import Vue from 'vue'

const $selects = {
    test_type: [
        {text: 'カリキュラムテスト', value: 0},
        {text: '総合テスト', value: 1},
        {text: 'CABテスト', value: 2}
    ],
    answer: [
        {text: '①', value: 1},
        {text: '②', value: 2},
        {text: '③', value: 3},
        {text: '④', value: 4}
    ],
    industry: [
        {text: '通信販売業', value: 1},
        {text: '金融／保険業', value: 2},
        {text: '通信業', value: 3},
        {text: '流通／小売業', value: 4},
        {text: '運輸業', value: 5},
        {text: '旅行業', value: 6},
        {text: '電力／ガス／水道', value: 7},
        {text: '製造業', value: 8},
        {text: 'サービス業', value: 9},
        {text: '医療／福祉', value: 10},
        {text: '建設／不動産業', value: 11},
        {text: '放送／出版／マスコミ', value: 12}
    ],
    job_status: [
        {text: '正社員', value: 0},
        {text: 'パート・アルバイト', value: 1},
        {text: '契約社員', value: 2},
        {text: '派遣社員', value: 3},
        {text: '個人事業主', value: 4},
    ],
    after_graduation_flg: [
        {text: '受講中', value: 0},
        {text: '完了（フロントエンド）', value: 1},
        {text: '完了（サーバーサイド）', value: 2},
        {text: '完了（その他）', value: 3},
        {text: '辞退', value: 4},
    ],
    gender: [
        {text: '未回答', value: null},
        {text: '男', value: 0},
        {text: '女', value: 1},
    ],
    academic_type: [
        {text: '中卒', value: 0},
        {text: '高卒', value: 1},
        {text: '専門卒', value: 2},
        {text: '短大卒(文系)', value: 3},
        {text: '短大卒(理系)', value: 4},
        {text: '大卒(文系)', value: 5},
        {text: '大卒(理系)', value: 6},
        {text: '大院卒(文系)', value: 7},
        {text: '大院卒(理系)', value: 8},
    ],
    state: [
        {value: 1, text: '北海道'},
        {value: 2, text: '青森県'},
        {value: 3, text: '岩手県'},
        {value: 4, text: '宮城県'},
        {value: 5, text: '秋田県'},
        {value: 6, text: '山形県'},
        {value: 7, text: '福島県'},
        {value: 8, text: '茨城県'},
        {value: 9, text: '栃木県'},
        {value: 10, text: '群馬県'},
        {value: 11, text: '埼玉県'},
        {value: 12, text: '千葉県'},
        {value: 13, text: '東京都'},
        {value: 14, text: '神奈川県'},
        {value: 15, text: '新潟県'},
        {value: 16, text: '富山県'},
        {value: 17, text: '石川県'},
        {value: 18, text: '福井県'},
        {value: 19, text: '山梨県'},
        {value: 20, text: '長野県'},
        {value: 21, text: '岐阜県'},
        {value: 22, text: '静岡県'},
        {value: 23, text: '愛知県'},
        {value: 24, text: '三重県'},
        {value: 25, text: '滋賀県'},
        {value: 26, text: '京都府'},
        {value: 27, text: '大阪府'},
        {value: 28, text: '兵庫県'},
        {value: 29, text: '奈良県'},
        {value: 30, text: '和歌山県'},
        {value: 31, text: '鳥取県'},
        {value: 32, text: '島根県'},
        {value: 33, text: '岡山県'},
        {value: 34, text: '広島県'},
        {value: 35, text: '山口県'},
        {value: 36, text: '徳島県'},
        {value: 37, text: '香川県'},
        {value: 38, text: '愛媛県'},
        {value: 39, text: '高知県'},
        {value: 40, text: '福岡県'},
        {value: 41, text: '佐賀県'},
        {value: 42, text: '長崎県'},
        {value: 43, text: '熊本県'},
        {value: 44, text: '大分県'},
        {value: 45, text: '宮崎県'},
        {value: 46, text: '鹿児島県'},
        {value: 47, text: '沖縄県'},
    ],
    yes_no: [
        {text: 'はい', value: 1},
        {text: 'いいえ', value: 0},
    ],
    have: [
        {text: '有', value:1},
        {text: '無', value:0},
    ],
    club_type:[
        {text: '無', value:0},
        {text: '運動部', value:1},
        {text: '文化部', value:2},
    ],
    attendance_reserve_flg:[
        {text: 'すべて', value:null},
        {text: '受講のみ', value:0},
    ],
    percents:[
        {text: '10%', value:10},
        {text: '20%', value:20},
        {text: '30%', value:30},
        {text: '40%', value:40},
        {text: '50%', value:50},
        {text: '60%', value:60},
        {text: '70%', value:70},
        {text: '80%', value:80},
        {text: '90%', value:90},
        {text: '100%', value:100},
    ],
    progress_status: [
        {text: '作業中', value:1},
        {text: '確認中', value:2},
        {text: '完了', value:3},
    ],
    student_progress_status: [
        {text: '作業中', value:1},
        {text: '完了', value:3},
    ],
    sales_evaluation: [
        {text: 1, value: 1},
        {text: 2, value: 2},
        {text: 3, value: 3},
        {text: 4, value: 4},
        {text: 5, value: 5}
    ],
    missing_type: [
        {text: '講師評価', value: 0},
        {text: '営業評価', value: 1},
        {text: '理解度', value: 2},
        {text: '思考力', value: 3},
        {text: '受講率', value: 4},
        {text: '報告率', value: 5},
        {text: '進捗率', value: 6},
    ]
};

Vue.prototype.$selects = $selects;
export default (context) => {
    context.$selects = $selects;
};
